<a href="https://colab.research.google.com/github/TensorCruncher/Pytorch-Course-By-Daniel-Bourke/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals

## Importing PyTorch

In [ ]:
import torch
print(torch.__version__)

2.3.1+cu121


## Introduction to tensors

### Creating tensors

In [ ]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the number from within the tensor (only works with one element tensors)
scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# Check shape of vector
vector.shape

torch.Size([2])

In [ ]:
# Matrix

MATRIX = torch.tensor([[1,2],
                      [3,4],
                       [5,6]])
MATRIX

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 2])

In [ ]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.3060, 0.3012, 0.8337, 0.4316],
        [0.0799, 0.7896, 0.2761, 0.9327],
        [0.5637, 0.8653, 0.5331, 0.8529]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# Create a random tensor of size (224, 224, 3)

random_image_size_tensor = torch.rand(size=(224,224,3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Creating a tensor of all ones

ones = torch.ones(size=(3,4))

ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range and tensors like

In [ ]:
# Creating a range
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Zeros Like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Ones Like
ten_ones = torch.ones_like(zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

In [ ]:
# Default dtype for tensors is float32

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype = None,
                              device=None,
                              requires_grad=False)

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=torch.half)
float_16_tensor.dtype

torch.float16

## Getting information from tensors

In [ ]:
# Create a random tensor

some_tensor = torch.rand(3,4)

print(some_tensor)
print(f"Shape: {some_tensor.shape}")
print(f"Dtype: {some_tensor.dtype}")
print(f"Device: {some_tensor.device}")

tensor([[0.1355, 0.6398, 0.7490, 0.6795],
        [0.4102, 0.4027, 0.8229, 0.7711],
        [0.5945, 0.2767, 0.0281, 0.3649]])
Shape: torch.Size([3, 4])
Dtype: torch.float32
Device: cpu


## Manipulating Tensors (Tensor Operations)

### Basic Operations

In [ ]:
# Addition

tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensor values don't change unless reassigned
# Subtraction
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor += 10
tensor

tensor([1, 2, 3])

In [ ]:
# Torch functions

torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Element wise multiplication

tensor * tensor

tensor([1, 4, 9])

### Matrix Multiplication (is all you need)

In [ ]:
# Comparing element wise multiplication and matrix multiplication (Dot poduct in this case)

tensor = torch.tensor([1,2,3])


In [ ]:
# Elemet wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix Multiplication (Dot product)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Using the @ symbol for matmul (not recommended)

tensor @ tensor

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
%%time
# Avoid using for loops for matmul
value = 0

for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value


CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 1.25 ms


tensor(14)

In [ ]:
%%time

torch.matmul(tensor, tensor)

CPU times: user 58 µs, sys: 10 µs, total: 68 µs
Wall time: 71 µs


tensor(14)

## One of the most common errors in deep learning (shape errors)

In [ ]:
# Shapes need to match (inner dim) for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype = torch.float32)
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]], dtype = torch.float32)

#torch.matmul(tensor_A, tensor_B)

In [ ]:
# View tensors A and B

print(tensor_A)

print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensors A and B transpose

print(tensor_A)

print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# Matrix Multiplication works when inner dimensions match

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# Create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find min value
x.min()

tensor(0)

In [ ]:
# Find max value
x.max()

tensor(90)

In [ ]:
# Find mean (needs to be float to work)

x.type(torch.float).mean()

tensor(45.)

In [ ]:
# Find sum

x.sum()

tensor(450)

In [ ]:
# Alternatively, use torch methods

torch.min(x), torch.max(x), torch.mean(x.type(torch.float)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

### Positional min / max

In [ ]:
# Create a tensor

tensor = torch.arange(0, 101, 10)

print(tensor)

# Return index of min and max element

print(f"Min: {tensor.argmin()}")
print(f"Max: {tensor.argmax()}")

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
Min: 0
Max: 10


### Change tensor datatype

In [ ]:
# Create a tensor and check dtype

tensor = torch.arange(10.,100., 10.)
tensor.dtype

torch.float32

In [ ]:
# Create a float16 tensor

tensor_float_16 = tensor.type(torch.half)
tensor_float_16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
# Create a int8 tensor

tensor_int_8 = tensor.type(torch.int8)
tensor_int_8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

In [ ]:
# Create a tensor

x = torch.arange(1.,8,)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension

x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps underlying data)

z = x.view(1,7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Changing z changes x

z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Stack tensors on top of each other

x_stacked = torch.stack([x,x,x,x], dim=0)

x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [ ]:
x_stacked.shape

torch.Size([4, 7])

In [ ]:
# Squeeze To Remove dimensions with only one value

print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()

print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous Shape: torch.Size([1, 7])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New Shape: torch.Size([7])


In [ ]:
# Unsqueeze To add dimension one value

print(f"Previous Tensor: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous Shape: torch.Size([7])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New Shape: torch.Size([1, 7])


In [ ]:
# Create a tensor

x_original = torch.rand(2,3,2)

x_original

tensor([[[0.2172, 0.3896],
         [0.1786, 0.5813],
         [0.0438, 0.4548]],

        [[0.9501, 0.4933],
         [0.1124, 0.7511],
         [0.0216, 0.7845]]])

In [ ]:
# Permute the original tensor to rearrange axis order

x_permuted = x_original.permute(2,0,1)

x_permuted

tensor([[[0.2172, 0.1786, 0.0438],
         [0.9501, 0.1124, 0.0216]],

        [[0.3896, 0.5813, 0.4548],
         [0.4933, 0.7511, 0.7845]]])

## Indexing (selecting data from tensors)

In [ ]:
# Create a tensor

x = torch.arange(1, 19).reshape(2, 3, 3)
x

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
# Indexing

print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")


First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension

x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([ 5, 14])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

## PyTorch Tensors and Numpy

In [111]:
# Numpy array to tensor

import numpy as np

array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array).type(torch.float)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [112]:
# Change array, keep tensor

array += 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [120]:
# Tensor to numpy array

tensor = torch.ones(5)

numpy_tensor = tensor.numpy().astype(float)

tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.]))

In [121]:
# Change tensor, keep array

tensor += 1

tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1.]))

## Reproducibility (trying to take the random out of random)

In [125]:
# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(f"Tensor A:\n {random_tensor_A}")
print(f"Tensor B:\n {random_tensor_B}")
print(f"Does Tensor A equal Tensor B anywhwere?\n {random_tensor_A == random_tensor_B}")

Tensor A:
 tensor([[0.3528, 0.2264, 0.4208, 0.0170],
        [0.9191, 0.9405, 0.6427, 0.9617],
        [0.4622, 0.0530, 0.2685, 0.7174]])
Tensor B:
 tensor([[0.6596, 0.1533, 0.6486, 0.6716],
        [0.5923, 0.6221, 0.3132, 0.1113],
        [0.4989, 0.0765, 0.7236, 0.7146]])
Does Tensor A equal Tensor B anywhwere?
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [126]:
# Set random seed

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(f"Tensor C:\n {random_tensor_C}")
print(f"Tensor D:\n {random_tensor_D}")
print(f"Does Tensor C equal Tensor D anywhwere?\n {random_tensor_C == random_tensor_D}")

Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Tensor D:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Does Tensor C equal Tensor D anywhwere?
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors on GPUs (and making faster computations)

In [3]:
import torch
torch.cuda.is_available()

True

In [4]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# Count number of devices
torch.cuda.device_count()

1

In [6]:
# Create tensor (default on CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
# Cannot use Numpy with tensor on GPU

#tensor_on_gpu.numpy()

In [12]:
# Copy tensor back to CPU

tensor_cpu = tensor_on_gpu.cpu().numpy()
tensor_cpu

array([1, 2, 3])

In [13]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')